# Generated by Django 2.0 on 2017-12-26 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cognome', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('codice_fiscale', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mail', models.EmailField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestazioni', models.CharField(default='', max_length=100)),
                ('prezzo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ripetizione1', models.IntegerField(default='1')),
                ('ripetizione2', models.IntegerField(default='1')),
                ('ripetizione3', models.IntegerField(default='1')),
                ('ripetizione4', models.IntegerField(default='1')),
                ('ripetizione5', models.IntegerField(default='1')),
                ('prezzo', models.IntegerField(default='0')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('prestazione1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazione1', to='app.Prestazione')),
                ('prestazione2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazione2', to='app.Prestazione')),
                ('prestazione3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazione3', to='app.Prestazione')),
                ('prestazione4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazione4', to='app.Prestazione')),
                ('prestazione5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazione5', to='app.Prestazione')),
            ],
        ),
    ]
