# Generated by Django 2.0.2 on 2018-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180109_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='indirizzo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
