# Generated by Django 2.0.2 on 2018-02-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cliente_indirizzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='prestazione10',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione10', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione11',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione11', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione12',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione12', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione13',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione13', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione14',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione14', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione15',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione15', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione6',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione6', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione7',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione7', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione8',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione8', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='prestazione9',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestazione9', to='app.Prestazione'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione10',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione11',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione12',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione13',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione14',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione15',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione6',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione7',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione8',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='ripetizione9',
            field=models.IntegerField(default=1),
        ),
    ]
